### ISSUE TITLE
Documentation on the Name Etymology

### ISSUE THREAD

**Issue by johnkanji** [dilevin/Bartels#1]
Could you please add some additional documentation on the origin of the name of the library. I did some googling, and I figure it must refer to Michael Bartels, the German FIA GT championship winning racing driver, but some clear documentation in the readme would be helpful, and may save others a google in the future :).

**Comment by dilevin** [comment]
Bartels was one of Gauss' academic advisers. Gauss was my previous attempt at a useful code base for physics-based animation research. I
