### ISSUE TITLE
Mex functions parsing degrees of freedom (q) as an index variable

### ISSUE THREAD

**Issue by tytrusty** [dilevin/Bartels#11]
In many mex functions, the  **q** DOF vector is being parsed as an index. For example:

https://github.com/dilevin/Bartels/blob/ae1aee26ac23d60a6cf988ce693e630dd007f1e8/matlab/linear_tetmesh_neohookean_q.cpp#L35

parse_rhs_index converts matlab index variables to 0-indexed for cpp:
```
igl::matlab::parse_rhs_index(...) {
  parse_rhs_double(prhs,V);
  V.array() -= 1;
}
```

Am I missing something or is this a bug? If this is a problem, I can submit a pull request to correct instances of this.

**Comment by dilevin** [comment]
thanks for finding this. these should be parse_rhs_double not parse_rhs_index. I guess the code was just translating everything to the left by one unit which doesn't really effect the physics. 

Good find.

**Comment by dilevin** [comment]
please submit a PR when you fix one of these
