### ISSUE TITLE
Naming inconsistency in shape function derivatives

### ISSUE THREAD

**Issue by abhimadan** [dilevin/Bartels#3]
In the `*_dphi_dX` functions, the output variable is named `dX`, but this same value is named `dXinv` in the `*_dq2` and `*_dq` functions. I think this is true for both the main source files and the mex wrappers.

**Comment by dilevin** [comment]
I've renamed all these variables as dphidX because they are the gradients of the shape functions (phi) with respect to the reference element configuration (X).
