### ISSUE TITLE
Non-const reference in Hessian function

### ISSUE THREAD

**Issue by abhimadan** [dilevin/Bartels#6]
I ran into a compile error because `V` is a non-const reference so I can't pass a const reference to it (though it could be in other functions as well - I haven't checked). Source:

https://github.com/dilevin/Bartels/blob/38adea7751b7a6b5cd6af75f597b6da0bb861649/include/linear_tri3dmesh_stvk_dq2.h#L19

**Comment by dilevin** [comment]
This should be fixed now
