### ISSUE TITLE
Unspecified order of Lamé parameters in d2psi_neohookean_dF2

### ISSUE THREAD

**Issue by WinterAlexander** [dilevin/Bartels#7]
d2psi_neohookean_dF2 takes a matrix of # of triangles/tet x 2 where each row contain (I believe) the 2 Lamé parameters. Yet since this file has no matlab documentation and its code is entirely generated with no comments, it is not easy to know which of the 2 params is the mu and the lambda. I would presume lambda and mu since they are called the first and the second Lamé parameters respectively but I do not know myself at the moment. Would be great to have a simple line comment or documentation block on the function.

**Comment by dilevin** [comment]
added both an argument checker and comments so that now help d2psi_neohookean_dF2 will return information on how the file works.
